### ISSUE TITLE
请问代码是怎么跟数据库连起来的呀？

### ISSUE THREAD

**Issue by WxFang** [danerlt/attend#2]
我只看到一个sql文件，但是没有看到META-INF里context.xml文件。

**Comment by danerlt** [comment]
你好，在main下有一个util包，下面有一个DBUtil.java文件，对JDBC做了一个小小的封装，你修改里面连接，用户名和密码就可以了

**Comment by danerlt** [comment]
@WxFang 你好，在main下有一个util包，下面有一个DBUtil.java文件，对JDBC做了一个小小的封装，你修改里面连接，用户名和密码就可以了
